#!/usr/bin/env python3
"""
ICS-Watchdog — Reporter (JSON/HTML Generation)

Reads the outputs generated by the passive watchdog (alerts.jsonl and packet_stats.json)
and generates a structured JSON report.
"""

import json
import os
import sys
from collections import Counter

OUTPUT_DIR = "/app/output"
ALERTS_FILE = os.path.join(OUTPUT_DIR, "alerts.jsonl")
STATS_FILE = os.path.join(OUTPUT_DIR, "packet_stats.json")
REPORT_JSON = os.path.join(OUTPUT_DIR, "watchdog_report.json")

def generate_json_report():
    if not os.path.exists(STATS_FILE) or not os.path.exists(ALERTS_FILE):
        print("Required output files from watchdog not found.")
        sys.exit(1)
        
    with open(STATS_FILE, "r") as f:
        stats = json.load(f)
        
    alerts = []
    with open(ALERTS_FILE, "r") as f:
        for line in f:
            if line.strip():
                alerts.append(json.loads(line))
                
    severity_counts = Counter(alert.get("severity", "UNKNOWN") for alert in alerts)
    
    report = {
        "summary": {
            "run_duration_seconds": stats.get("elapsed_seconds", 0),
            "total_packets_captured": stats.get("total_packets", 0),
            "modbus_packets": stats.get("modbus_packets", 0),
            "total_alerts": len(alerts),
            "alerts_by_severity": dict(severity_counts)
        },
        "network_stats": {
            "function_codes": stats.get("function_code_distribution", {}),
            "source_ips": stats.get("source_ips", {}),
            "destination_ips": stats.get("destination_ips", {})
        },
        "alerts": alerts
    }
    
    with open(REPORT_JSON, "w") as f:
        json.dump(report, f, indent=2)
        
    print(f"JSON report generated at {REPORT_JSON}")
    
    # Generate HTML report
    try:
        from jinja2 import Environment, FileSystemLoader
        env = Environment(loader=FileSystemLoader("/app/templates"))
        template = env.get_template("report.html.j2")
        html_content = template.render(report=report)
        
        report_html = os.path.join(OUTPUT_DIR, "watchdog_report.html")
        with open(report_html, "w") as f:
            f.write(html_content)
            
        print(f"HTML report generated at {report_html}")
    except Exception as e:
        print(f"Failed to generate HTML report: {e}")

if __name__ == "__main__":
    generate_json_report()
